# Generated by Django 3.2.6 on 2021-10-07 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 7, 12, 59, 34, 977347)),
        ),
    ]
