# Generated by Django 3.2.6 on 2021-10-10 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211008_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 11, 30, 23, 67273)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img_author',
            field=models.ImageField(upload_to='author_img/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img_blog',
            field=models.ImageField(upload_to='blog_img/'),
        ),
    ]
